using Npgsql;
using Zapara.Server.Accounts;

namespace Zapara.Server.Communities;

internal static class MessengerSchema
{
    public static async Task EnsureAsync(AccountsDataSource data, CommunitiesConfiguration configuration, CancellationToken ct)
    {
        await using var connection = data.CreateConnection();
        await connection.OpenAsync(ct);
        await using (var probe = new NpgsqlCommand("SELECT to_regclass(@name)::text", connection))
        {
            probe.Parameters.AddWithValue("name", configuration.Schema + ".communities");
            if (await probe.ExecuteScalarAsync(ct) is null or DBNull or "") return;
        }
        var sql = """
            CREATE SCHEMA IF NOT EXISTS __MSG__;
            CREATE TABLE IF NOT EXISTS __MSG__.conversations (
                conversation_id uuid PRIMARY KEY,
                kind text NOT NULL CHECK (kind IN ('direct','group')),
                community_id uuid NOT NULL REFERENCES __COM__.communities(community_id),
                direct_key text NULL,
                created_at timestamptz NOT NULL,
                CHECK ((kind = 'group' AND direct_key IS NULL) OR (kind = 'direct' AND direct_key IS NOT NULL))
            );
            CREATE TABLE IF NOT EXISTS __MSG__.conversation_members (
                conversation_id uuid NOT NULL REFERENCES __MSG__.conversations(conversation_id),
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                joined_at timestamptz NOT NULL,
                last_read_no bigint NOT NULL DEFAULT 0,
                PRIMARY KEY (conversation_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.chat_messages (
                message_id uuid PRIMARY KEY,
                conversation_id uuid NOT NULL REFERENCES __MSG__.conversations(conversation_id),
                sender_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id),
                body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000 AND translate(body, E'\n\t', '') !~ '[[:cntrl:]]'),
                created_at timestamptz NOT NULL,
                message_no bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL
            );
            ALTER TABLE __MSG__.chat_messages ADD COLUMN IF NOT EXISTS message_no bigint GENERATED BY DEFAULT AS IDENTITY;
            DO $zapara_msg$
            DECLARE
                msg text := '__RAWMSG__';
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_attribute a
                    JOIN pg_class c ON c.oid = a.attrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE n.nspname = msg AND c.relname = 'conversation_members'
                      AND a.attname = 'last_read_no' AND a.attnum > 0 AND NOT a.attisdropped
                ) THEN
                    BEGIN
                        EXECUTE format('ALTER TABLE %I.conversation_members ADD COLUMN last_read_no bigint NOT NULL DEFAULT 0', msg);
                        EXECUTE format('UPDATE %I.conversation_members AS member SET last_read_no = COALESCE((SELECT MAX(message_no) FROM %I.chat_messages AS message WHERE message.conversation_id = member.conversation_id), 0)', msg, msg);
                    EXCEPTION
                        WHEN duplicate_column THEN NULL;
                    END;
                END IF;
            END
            $zapara_msg$;
            DROP INDEX IF EXISTS __MSG__.conversations_group;
            DROP INDEX IF EXISTS __MSG__.conversations_direct;
            CREATE UNIQUE INDEX conversations_group ON __MSG__.conversations(community_id) WHERE kind = 'group';
            CREATE UNIQUE INDEX conversations_direct ON __MSG__.conversations(community_id, direct_key) WHERE kind = 'direct';
            DROP INDEX IF EXISTS __MSG__.chat_messages_conversation;
            CREATE INDEX chat_messages_conversation ON __MSG__.chat_messages(conversation_id, message_no);
            ALTER TABLE __MSG__.chat_messages ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'text';
            ALTER TABLE __MSG__.chat_messages ADD COLUMN IF NOT EXISTS deleted boolean NOT NULL DEFAULT false;
            ALTER TABLE __MSG__.chat_messages ADD COLUMN IF NOT EXISTS reply_to uuid;
            ALTER TABLE __MSG__.chat_messages ADD COLUMN IF NOT EXISTS topic_id uuid;
            CREATE TABLE IF NOT EXISTS __MSG__.chat_reactions (
                message_id uuid NOT NULL REFERENCES __MSG__.chat_messages(message_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                emoji text NOT NULL,
                PRIMARY KEY (message_id, user_id)
            );
            CREATE INDEX IF NOT EXISTS chat_messages_topic ON __MSG__.chat_messages (topic_id, message_no);
            CREATE TABLE IF NOT EXISTS __MSG__.group_topics (
                topic_id uuid PRIMARY KEY,
                community_id uuid NOT NULL REFERENCES __COM__.communities(community_id) ON DELETE CASCADE,
                title text NOT NULL CHECK (char_length(title) BETWEEN 2 AND 40),
                icon text NOT NULL CHECK (char_length(icon) BETWEEN 1 AND 8),
                kind text NOT NULL DEFAULT 'chat' CHECK (kind IN ('chat','ballots')),
                description text NOT NULL DEFAULT '' CHECK (char_length(description) <= 240),
                accent text NOT NULL DEFAULT 'default' CHECK (accent IN ('default','blue','green','purple','orange','red')),
                pinned boolean NOT NULL DEFAULT false,
                write_policy text NOT NULL DEFAULT 'all' CHECK (write_policy IN ('all','managers')),
                created_by uuid NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE SET NULL,
                created_at timestamptz NOT NULL
            );
            ALTER TABLE __MSG__.group_topics ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'chat';
            ALTER TABLE __MSG__.group_topics ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';
            ALTER TABLE __MSG__.group_topics ADD COLUMN IF NOT EXISTS accent text NOT NULL DEFAULT 'default';
            ALTER TABLE __MSG__.group_topics ADD COLUMN IF NOT EXISTS pinned boolean NOT NULL DEFAULT false;
            ALTER TABLE __MSG__.group_topics ADD COLUMN IF NOT EXISTS write_policy text NOT NULL DEFAULT 'all';
            DO $zapara_topic_kind$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_topics'::regclass AND conname='group_topics_kind_check') THEN
                    ALTER TABLE __MSG__.group_topics ADD CONSTRAINT group_topics_kind_check CHECK (kind IN ('chat','ballots'));
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_topics'::regclass AND conname='group_topics_description_check') THEN
                    ALTER TABLE __MSG__.group_topics ADD CONSTRAINT group_topics_description_check CHECK (char_length(description) <= 240);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_topics'::regclass AND conname='group_topics_accent_check') THEN
                    ALTER TABLE __MSG__.group_topics ADD CONSTRAINT group_topics_accent_check CHECK (accent IN ('default','blue','green','purple','orange','red'));
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_topics'::regclass AND conname='group_topics_write_policy_check') THEN
                    ALTER TABLE __MSG__.group_topics ADD CONSTRAINT group_topics_write_policy_check CHECK (write_policy IN ('all','managers'));
                END IF;
            END
            $zapara_topic_kind$;
            CREATE UNIQUE INDEX IF NOT EXISTS group_topics_ci ON __MSG__.group_topics (community_id, lower(title));
            CREATE TABLE IF NOT EXISTS __MSG__.group_topic_reads (
                community_id uuid NOT NULL REFERENCES __COM__.communities(community_id) ON DELETE CASCADE,
                topic_id uuid NOT NULL,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                last_read_no bigint NOT NULL,
                PRIMARY KEY (community_id, topic_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.group_roles (
                role_id uuid PRIMARY KEY,
                community_id uuid NOT NULL REFERENCES __COM__.communities(community_id) ON DELETE CASCADE,
                name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 32),
                created_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS group_roles_ci ON __MSG__.group_roles (community_id, lower(name));
            CREATE TABLE IF NOT EXISTS __MSG__.group_role_grants (
                role_id uuid NOT NULL REFERENCES __MSG__.group_roles(role_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                PRIMARY KEY (role_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.ballots (
                ballot_id uuid PRIMARY KEY,
                community_id uuid NOT NULL REFERENCES __COM__.communities(community_id) ON DELETE CASCADE,
                topic_id uuid NULL REFERENCES __MSG__.group_topics(topic_id) ON DELETE SET NULL,
                question text NOT NULL CHECK (char_length(question) BETWEEN 1 AND 400),
                origin text NOT NULL CHECK (origin IN ('system','headman','collective')),
                status text NOT NULL CHECK (status IN ('collecting','open','closed')),
                deadline_at timestamptz NOT NULL,
                opened_at timestamptz NULL,
                created_by uuid NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE SET NULL,
                created_at timestamptz NOT NULL
            );
            ALTER TABLE __MSG__.ballots ADD COLUMN IF NOT EXISTS topic_id uuid;
            DO $zapara_ballot_topic$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.ballots'::regclass AND conname='ballots_topic_id_fkey') THEN
                    ALTER TABLE __MSG__.ballots ADD CONSTRAINT ballots_topic_id_fkey
                        FOREIGN KEY (topic_id) REFERENCES __MSG__.group_topics(topic_id) ON DELETE SET NULL;
                END IF;
            END
            $zapara_ballot_topic$;
            CREATE INDEX IF NOT EXISTS ballots_community ON __MSG__.ballots (community_id, created_at DESC);
            CREATE INDEX IF NOT EXISTS ballots_topic ON __MSG__.ballots (community_id, topic_id, created_at DESC);
            CREATE TABLE IF NOT EXISTS __MSG__.ballot_options (
                option_id uuid PRIMARY KEY,
                ballot_id uuid NOT NULL REFERENCES __MSG__.ballots(ballot_id) ON DELETE CASCADE,
                label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 80),
                ordinal integer NOT NULL CHECK (ordinal >= 0 AND ordinal < 16),
                UNIQUE (ballot_id, ordinal)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.ballot_support (
                ballot_id uuid NOT NULL REFERENCES __MSG__.ballots(ballot_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                created_at timestamptz NOT NULL,
                PRIMARY KEY (ballot_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.ballot_votes (
                ballot_id uuid NOT NULL REFERENCES __MSG__.ballots(ballot_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                option_id uuid NOT NULL,
                updated_at timestamptz NOT NULL,
                PRIMARY KEY (ballot_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __MSG__.group_role_powers (
                role_id uuid NOT NULL REFERENCES __MSG__.group_roles(role_id) ON DELETE CASCADE,
                power text NOT NULL CHECK (power IN ('joins','exclude','roles','grants','ballots','close','channels')),
                PRIMARY KEY (role_id, power)
            );
            DO $zapara_role_power$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_role_powers'::regclass
                      AND conname='group_role_powers_power_check'
                      AND pg_get_constraintdef(oid) NOT LIKE '%channels%') THEN
                    ALTER TABLE __MSG__.group_role_powers DROP CONSTRAINT group_role_powers_power_check;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid='__MSG__.group_role_powers'::regclass AND conname='group_role_powers_power_check') THEN
                    ALTER TABLE __MSG__.group_role_powers ADD CONSTRAINT group_role_powers_power_check
                        CHECK (power IN ('joins','exclude','roles','grants','ballots','close','channels'));
                END IF;
            END
            $zapara_role_power$;
            CREATE TABLE IF NOT EXISTS __MSG__.ballot_effects (
                ballot_id uuid PRIMARY KEY REFERENCES __MSG__.ballots(ballot_id) ON DELETE CASCADE,
                kind text NOT NULL CHECK (kind IN ('power','grant','revoke_grant','create_role','rename_role','delete_role','remove_member')),
                payload text NOT NULL CHECK (char_length(payload) BETWEEN 2 AND 800),
                outcome text NULL CHECK (outcome IS NULL OR outcome IN ('accepted','rejected','skipped')),
                applied_at timestamptz NULL
            );
            """.Replace("__RAWMSG__", configuration.MessagesSchema, StringComparison.Ordinal)
            .Replace("__MSG__", configuration.QuotedMessages, StringComparison.Ordinal)
            .Replace("__COM__", configuration.QuotedSchema, StringComparison.Ordinal)
            .Replace("__ACCOUNTS__", configuration.Accounts.QuotedSchema, StringComparison.Ordinal);
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(ct);
    }
}

internal sealed class MessengerSchemaService(AccountsDataSource data, CommunitiesConfiguration configuration) : Microsoft.Extensions.Hosting.IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken) => MessengerSchema.EnsureAsync(data, configuration, cancellationToken);
    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
