import { useState } from "react";
import { Link } from "react-router-dom";
import * as api from "./api";
import { useApp } from "./store";
import { useConnectivity } from "./ux300-controls";

const kindNames:Record<string,string>={homework:"Задания",completion:"Готовность",settings:"Настройки"};
const fieldNames:Record<string,string>={subjectRaw:"Предмет",text:"Задание",targetNthOccurrence:"Номер занятия",createdAtUtc:"Создано",legacyCreatedLocalDate:"Исходная дата",done:"Выполнено",doneAtUtc:"Отметка сделана",selectedGroupId:"Группа",parityInvert:"Инвертировать чётность",notifyTime1:"Утреннее напоминание",notifyTime2:"Вечернее напоминание",strictness:"Точность пересечений",alwaysShow:"Группы без совпадений"};
function fields(value:unknown){if(!value||typeof value!=="object")return [];return Object.entries(value).filter(([key])=>fieldNames[key]);}
function display(value:unknown){return value===null?"Не указано":typeof value==="boolean"?value?"Да":"Нет":String(value);}
export function DataSettings(){
  const app=useApp();const cache=api.readCache();const online=useConnectivity();
  const [state,setState]=useState("");const[busy,setBusy]=useState(false);const[filter,setFilter]=useState("all");
  const conflicts=app.privateHomework.pending.filter(row=>row.conflict!==undefined);
  const visible=conflicts.filter(row=>filter==="all"||row.type===filter);
  return <article className="card stack"><h2>Копия на устройстве</h2><p>{Object.keys(cache.lessons).length} сохранённых расписаний · {app.homework.length} личных заданий</p><p className="muted">Подключение: {online?"сеть доступна":"нет сети"}. {cache.lessons[app.groupId]?`Копия расписания: ${new Date(cache.lessons[app.groupId].meta.fetchedAt).toLocaleString("ru-RU")}`:"Расписание ещё не сохранено."}</p><button className="btn" disabled={app.loading||app.timetableLoading} onClick={app.refresh}>Обновить расписание</button><h2>Синхронизация аккаунта</h2><p role="status">{app.privateHomework.status}</p>{app.session?.authenticated?<><button className="btn" disabled={busy} onClick={()=>{setBusy(true);void api.syncMetadata().then(()=>setState("Сервер синхронизации доступен")).catch(()=>setState("Сервер синхронизации недоступен. Локальная копия сохранена.")).finally(()=>setBusy(false));}}>{busy?"Проверяем…":"Проверить подключение"}</button><p role="status">{state}</p><button className="btn" onClick={app.privateHomework.refresh}>Синхронизировать личную домашку</button><button className="btn quiet" onClick={()=>{if(window.confirm("Скопировать гостевые задания в этот аккаунт? Гостевая копия останется на устройстве."))app.privateHomework.importGuest();}}>Импортировать гостевые задания</button>
    <details><summary>Ожидают отправки · {app.privateHomework.pending.length}</summary><div className="stack">{app.privateHomework.pending.map(row=><div className="card" key={row.opId}><b>{kindNames[row.type]||"Изменение"}{row.action==="delete"?" · удаление":""}</b><p>{app.homework.find(item=>item.id===row.id)?.subject||fields(row.value).filter(([key])=>key==="subjectRaw").map(([,value])=>display(value)).join("")}</p><p className="muted">{row.conflict!==undefined?"Нужно выбрать версию":"Сохранено на устройстве, ожидает синхронизации"}</p>{row.type!=="settings"&&app.homework.some(item=>item.id===row.id)&&<Link className="btn quiet" to={`/homework?id=${encodeURIComponent(row.id)}`}>Открыть задание</Link>}</div>)}</div></details>
    {conflicts.length>0&&<><label className="field">Конфликты<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">Все типы</option>{Object.entries(kindNames).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></label>{!visible.length&&<div role="status">Для выбранного типа конфликтов больше нет.<button className="btn" onClick={()=>setFilter("all")}>Показать остальные</button></div>}{visible.map(row=>{const local=Object.fromEntries(fields(row.value)),server=Object.fromEntries(fields(row.conflict?.value));const keys=[...new Set([...Object.keys(local),...Object.keys(server)])];return <div className="card stack" key={row.opId}><h3>{kindNames[row.type]} · выбор версии</h3><p>{row.action==="delete"?"Ваша версия: удалить запись":"Ваши изменения сохранены на устройстве."}</p>{(!row.conflict||row.conflict.tombstone)&&<p>На сервере запись отсутствует или удалена.</p>}<div className="stack">{keys.map(key=><div className="card" key={key}><b>{fieldNames[key]}</b><p>На устройстве: {display(local[key]??null)}</p><p>На сервере: {display(server[key]??null)}</p></div>)}</div><div className="row"><button className="btn" onClick={()=>app.privateHomework.resolve(row.opId,"server",row.conflict?.revision??null)}>Оставить серверную версию</button><button className="btn" onClick={()=>app.privateHomework.resolve(row.opId,"local",row.conflict?.revision??null)}>Сохранить мою версию</button></div></div>;})}</>}
    </>:<><p className="muted">Вход не переносит гостевые данные в аккаунт автоматически.</p><Link className="btn" to="/settings?section=account" state={{authReturnTo:"/settings?section=data"}}>Войти и вернуться к данным</Link></>}<p className="muted">Ошибка обновления не удаляет последнюю сохранённую копию расписания.</p></article>;
}
