import assert from "node:assert/strict";
import { test } from "node:test";
import { readFile } from "node:fs/promises";
import { runInNewContext } from "node:vm";
import ts from "typescript";
import * as revocation from "./draft-revocation.ts";
import { clearSentGroupDraft } from "./groupChat.ts";
import { advanceDraftEpoch,currentDraftEpoch,attachDiscussionContext,clearSentDiscussionContext,draftEpochMatches,draftKey } from "./draft-store.ts";
const source=ts.transpileModule(await readFile(new URL("./draft-store.ts",import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function openDraft<T>(memory:Map<string,string>,key:string,initial:T){
    const listeners=new Set<(event:any)=>void>();const effects:(()=>void)[]=[];
    const context={exports:{} as any,require:(id:string)=>id==="react"?({useState:(init:any)=>[typeof init==="function"?init():init,()=>{}],useRef:(value:any)=>({current:value}),useEffect:(fn:any)=>effects.push(fn)}):revocation,sessionStorage:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)},window:{dispatchEvent:(event:any)=>{listeners.forEach(listener=>listener(event));return true;},addEventListener:(_name:string,listener:any)=>listeners.add(listener),removeEventListener:(_name:string,listener:any)=>listeners.delete(listener)},CustomEvent:class{detail:string;constructor(_name:string,init:{detail:string}){this.detail=init.detail;}}};
    runInNewContext(source,context);const hook=context.exports.useStoredDraft(key,()=>initial);effects.forEach(effect=>effect());return hook as [T,(value:any)=>void,(expected:T,replacement?:T)=>boolean,(field:keyof T,next:any)=>void];
}
test("restored untouched chat draft clears after send while edited draft remains",()=>{assert.equal(draftEpochMatches(undefined,0),true);assert.deepEqual(clearSentGroupDraft({topic:"restored"},"topic","restored",draftEpochMatches(undefined,0)),{topic:""});assert.equal(draftEpochMatches(1,0),false);assert.deepEqual(clearSentGroupDraft({topic:"new text"},"topic","restored",draftEpochMatches(1,0)),{topic:"new text"});});
test("actual stored draft hook restores chat text and context after remount independently",()=>{
    const memory=new Map<string,string>();const text=openDraft(memory,"zapara.group.drafts",{} as Record<string,string>),context=openDraft(memory,"zapara.group.contexts",{} as Record<string,string>);text[1]({"account:conversation:topic":"Черновик"});context[1](attachDiscussionContext({},"account:conversation:topic","Пара · 2026-09-29",true));assert.equal(openDraft(memory,"zapara.group.drafts",{} as Record<string,string>)[0]["account:conversation:topic"],"Черновик");assert.equal(openDraft(memory,"zapara.group.contexts",{} as Record<string,string>)[0]["account:conversation:topic"],"Пара · 2026-09-29");context[1]((values:Record<string,string>)=>clearSentDiscussionContext(values,"account:conversation:topic","Пара · 2026-09-29"));assert.equal(openDraft(memory,"zapara.group.drafts",{} as Record<string,string>)[0]["account:conversation:topic"],"Черновик");assert.equal(openDraft(memory,"zapara.group.contexts",{} as Record<string,string>)[0]["account:conversation:topic"],"");
});
test("specialized drafts restore by owner/community/topic/form and clear only acknowledged version",()=>{
    const memory=new Map<string,string>();const variants=[{kind:"form-create",value:{title:"Анкета",description:"Описание",deadline:"2026-09-29T12:00",anonymous:true,questions:[{id:"q",options:["А","Б"]}]}},{kind:"form-answer",value:[{questionId:"q",text:"Мой ответ",choices:[]}]},{kind:"homework-create",value:{title:"Предмет",body:"Задание",deadline:"2026-09-29T12:00"}},{kind:"material-link",value:"https://example.test/material"}];
    for(const variant of variants){const key=draftKey("owner","community","topic",variant.kind,"form");const hook=openDraft(memory,key,null as any);hook[1](variant.value);assert.deepEqual(JSON.parse(JSON.stringify(openDraft(memory,key,null as any)[0])),variant.value);assert.equal(openDraft(memory,draftKey("other-owner","community","topic",variant.kind,"form"),null as any)[0],null);assert.equal(openDraft(memory,draftKey("owner","community","other-topic",variant.kind,"form"),null as any)[0],null);hook[1]({changed:"during send"});assert.equal(hook[2](variant.value),false);assert.deepEqual(JSON.parse(memory.get(key)!),{changed:"during send"});assert.equal(hook[2]({changed:"during send"}),true);assert.equal(memory.has(key),false);}
});
test("context acknowledgement preserves a changed context and a different channel",()=>{const values={one:"Новая пара",two:"Домашка"};assert.equal(clearSentDiscussionContext(values,"one","Старая пара"),values);assert.deepEqual(clearSentDiscussionContext(values,"two","Домашка"),{one:"Новая пара",two:""});});

test("persisted epochs protect edits after remount even if the new text equals the sent text",()=>{const values=new Map<string,string>();const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)};assert.equal(currentDraftEpoch(storage,"owner:topic"),0);advanceDraftEpoch(storage,"owner:topic");const sent=currentDraftEpoch(storage,"owner:topic");assert.equal(draftEpochMatches(currentDraftEpoch(storage,"owner:topic"),sent),true);advanceDraftEpoch(storage,"owner:topic");assert.equal(draftEpochMatches(currentDraftEpoch(storage,"owner:topic"),sent),false);assert.equal(currentDraftEpoch(storage,"other:topic"),0);});
test("actual draft hook rejects late setters/ACK after scoped revoke without harming B",()=>{const memory=new Map<string,string>();const aKey=draftKey("owner","c","A","form-answer","f"),bKey=draftKey("owner","c","B","material-link");const a=openDraft(memory,aKey,[{text:"old secret"}]),b=openDraft(memory,bKey,"");a[1]([{text:"A secret"}]);b[1]("B link");const storage={getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)};revocation.purgeGroupDrafts(storage,{owner:"owner",community:"c",topic:"A"});a[1]([{text:"late forbidden A"}]);assert.equal(a[2]([{text:"A secret"}]),false);assert.equal(memory.has(aKey),false);assert.equal(memory.get(bKey),'"B link"');});
