import assert from "node:assert/strict";
import { test } from "node:test";
import * as api from "./api.ts";
import { canComposeChannel, canCreateBallot, isChatChannel, topicPreview } from "./channels.ts";
import type { GroupTopic } from "./types";
const topic:GroupTopic={topicId:"t",title:"Тема",icon:"",kind:"chat",description:"",accent:"default",pinned:false,writePolicy:"all",lastBody:null,lastAuthor:null,lastAt:null,unread:0,canDelete:false,activeBallots:0,canPost:true};
test("unknown and archived kinds never become writable chats",()=>{assert.equal(isChatChannel({...topic,kind:"forms"}),false);assert.equal(isChatChannel({...topic,kind:"unknown",supported:false}),false);assert.equal(canComposeChannel({...topic,archived:true}),false);assert.equal(canComposeChannel({...topic,supported:false}),false);assert.equal(canCreateBallot({...topic,kind:"ballots",permissions:["read","vote"]},true),false);assert.equal(topicPreview({...topic,kind:"materials"}),"Файлы и ссылки");});
test("space DTO stays typed and endpoints carry negotiated header only for community scope",async()=>{const original=globalThis.fetch;const calls:{url:string;body:unknown;headers:Record<string,string>}[]=[];globalThis.fetch=async(input,init)=>{calls.push({url:String(input),body:init?.body?JSON.parse(String(init.body)):null,headers:init?.headers as Record<string,string>});return Response.json({topics:[],categories:[],desk:{},capabilities:{}});};try{await api.groupSpace("c");await api.saveCategory("c",null,"Учёба",2);await api.saveTopicAccess("c","t",[{roleId:"r",power:"read",state:"deny"}],7);await api.archiveTopic("c","t",true,8);await api.previewPermissions("c",{userId:"u",roleId:null});await api.loadGroups();assert.equal(calls[0].url,"/web-api/communities/c/space");assert.deepEqual(calls[1].body,{categoryId:null,title:"Учёба",position:2,expectedRevision:0});assert.deepEqual(calls[2].body,{rules:[{roleId:"r",power:"read",state:"deny"}],expectedRevision:7});assert.equal(calls[0].headers["X-Zapara-Group-Space"],"1");assert.equal(calls[5].headers["X-Zapara-Group-Space"],undefined);}finally{globalThis.fetch=original;}});
test("forms and shared homework send UTC canonical date, topic linkage and revisions",async()=>{const original=globalThis.fetch;const calls:{url:string;body:any}[]=[];globalThis.fetch=async(input,init)=>{calls.push({url:String(input),body:init?.body?JSON.parse(String(init.body)):null});return Response.json({forms:[]});};try{await api.shareHomework("c","Математика","Задание","2026-09-26T10:00:00.120Z","t");await api.groupHomework("c","t");await api.createGroupForm("c","t",{title:"Анкета",description:"",deadlineAt:null,anonymous:true,questions:[{questionId:"q",title:"Текст",kind:"shortText",required:true,options:[]}]});await api.submitGroupForm("c","f",[{questionId:"q",text:"Ответ",choices:[]}]);assert.equal(calls[0].body.deadlineAt,"2026-09-26T10:00:00.12Z");assert.equal(calls[0].body.topicId,"t");assert.equal(calls[1].url,"/web-api/communities/c/homework/copies?topicId=t");assert.equal(calls[2].body.anonymous,true);assert.deepEqual(calls[3].body,{answers:[{questionId:"q",text:"Ответ",choices:[]}]});}finally{globalThis.fetch=original;}});
