import {useLayoutEffect,useRef,useState} from 'react';
import * as api from './api';
import {useApp} from './store';
import {scopeLease,scopeLeaseValid} from './draft-revocation';
import {useClock} from './ux300-controls';
import {collectObligations,obligationNeedsMe,withGlobalBallots,GLOBAL_BALLOTS,type Obligation} from './group-obligations';
import type {GroupTopic,BallotBoard} from './types';
type Result=NonNullable<Awaited<ReturnType<typeof collectObligations>>>;
export function GroupObligations({communityId,onOpen}:{communityId:string;onOpen:(topic:GroupTopic|null,target:Obligation,board?:BallotBoard)=>void}){const app=useApp();const owner=app.session?.user?.userId||'';const scope=JSON.stringify([owner,app.session?.familyId,app.groupId,communityId]);const live=useRef(scope);live.current=scope;const serial=useRef(0),pending=useRef(false),mounted=useRef(true);const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState<'calendar'|'mine'>('mine');const now=useClock();
 useLayoutEffect(()=>{mounted.current=true;return()=>{mounted.current=false;serial.current++;pending.current=false;};},[scope]);
 async function refresh(){if(pending.current)return;pending.current=true;setBusy(true);setError('');const token=++serial.current,auth=api.authGeneration(),access={owner,community:communityId},lease=scopeLease(sessionStorage,access);const current=()=>mounted.current&&live.current===scope&&serial.current===token&&api.authGeneration()===auth&&scopeLeaseValid(sessionStorage,access,lease);
  try{const page=await api.topics(communityId);if(!current())return;const value=await collectObligations(withGlobalBallots(page.topics),result?.rows||[],current,async topic=>{
   const topicAccess=topic.topicId===GLOBAL_BALLOTS?access:{...access,topic:topic.topicId!},topicLease=scopeLease(sessionStorage,topicAccess);const readCurrent=()=>{if(!scopeLeaseValid(sessionStorage,topicAccess,topicLease))throw Error('403');};
   if(topic.kind==='forms'){const data=await api.groupForms(communityId,topic.topicId!);readCurrent();return data.forms.map(row=>({id:row.formId,source:topic.topicId!,kind:'form' as const,title:row.title,deadline:row.deadlineAt,needed:row.canRespond&&!row.ownResponse&&(!topic.permissions||topic.permissions.includes('formsRespond'))}));}
   if(topic.kind==='homework'){const data=await api.groupHomework(communityId,topic.topicId!);readCurrent();return data.map(row=>({id:row.homeworkId,source:topic.topicId!,kind:'homework' as const,title:row.title,deadline:row.deadlineAt||null,needed:!row.completed&&row.canComplete!==false}));}
   const data=await api.ballots(communityId,topic.topicId===GLOBAL_BALLOTS?undefined:topic.topicId!);readCurrent();return data.ballots.filter(row=>topic.topicId!==GLOBAL_BALLOTS||row.topicId==null).map(row=>({id:row.ballotId,source:topic.topicId!,kind:'ballot' as const,title:row.question,deadline:row.deadlineAt,needed:!topic.permissions||topic.permissions.includes('vote')?(row.status==='open'&&!row.options.some(option=>option.chosen)||row.status==='collecting'&&!row.supported):false}));
  });if(current()&&value)setResult(value);
  }catch(reason){if(!current())return;const status=reason instanceof Error?reason.message:'';if(['401','403','404'].includes(status)){setResult(null);}else setResult(value=>value?{...value,rows:value.rows.map(row=>({...row,stale:true}))}:null);setError('Обзор не обновился. Доступность разделов нужно проверить повторно.');}finally{if(mounted.current&&live.current===scope&&serial.current===token){if(!current()){setResult(null);setError('Профиль или доступ изменился. Обновите обзор.');}pending.current=false;setBusy(false);}}}
 async function open(row:Obligation){if(pending.current||row.stale)return;const token=++serial.current,auth=api.authGeneration(),access=row.source===GLOBAL_BALLOTS?{owner,community:communityId}:{owner,community:communityId,topic:row.source||'general'},lease=scopeLease(sessionStorage,access);const current=()=>mounted.current&&live.current===scope&&serial.current===token&&api.authGeneration()===auth&&scopeLeaseValid(sessionStorage,access,lease);pending.current=true;setBusy(true);try{if(row.source===GLOBAL_BALLOTS){const board=await api.ballots(communityId);if(!current())return;if(!board.ballots.some(item=>item.ballotId===row.id&&item.topicId==null)){setError('Голосование больше недоступно. Обновите обзор.');return;}onOpen(null,row,board);return;}const page=await api.topics(communityId);if(!current())return;const topic=page.topics.find(topic=>(topic.topicId||'')===row.source&&!topic.archived&&topic.supported!==false);if(!topic){setResult(value=>value?{...value,rows:value.rows.filter(item=>item.source!==row.source)}:null);setError('Раздел больше недоступен.');return;}onOpen(topic,row);}catch{if(current())setError('Доступ к разделу не подтвердился. Повторите обновление обзора.');}finally{if(mounted.current&&live.current===scope&&serial.current===token){pending.current=false;setBusy(false);}}}
 const rows=(result?.rows||[]).filter(row=>mode==='calendar'||obligationNeedsMe(row,now)).sort((a,b)=>{const left=a.deadline?Date.parse(a.deadline):Infinity,right=b.deadline?Date.parse(b.deadline):Infinity;return (Number.isFinite(left)?left:Infinity)-(Number.isFinite(right)?right:Infinity)||a.title.localeCompare(b.title,'ru');});
 return <details className="card stack"><summary>Сроки и мои обязательства в группе</summary><p className="muted">Общая доска голосований и до 22 доступных разделов: анкеты, голосования, домашка и непрочитанные чаты. Не более 24 запросов за обновление, включая список разделов; чужие ответы не запрашиваются.</p><button className="btn" disabled={busy} onClick={()=>void refresh()}>{busy?'Читаем доступные разделы…':'Обновить обзор обязательств'}</button><div className="seg"><button aria-pressed={mode==='mine'} onClick={()=>setMode('mine')}>Нужно мне</button><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}>Все сроки</button></div>{error&&<p role="status">{error}</p>}{result&&<p role="status">Источников прочитано: {result.loaded} из {result.total} · ошибки: {result.failed} · за пределами лимита: {result.skipped}</p>}{result&&!rows.length&&<p>В прочитанной части подходящих обязательств нет.</p>}{rows.map(row=><article className="card stack" key={row.kind+row.id}><b>{row.title}</b><span>{({form:'Анкета',ballot:'Голосование',homework:'Домашка',chat:'Непрочитанный чат'})[row.kind]} · {row.deadline&&Number.isFinite(Date.parse(row.deadline))?new Date(row.deadline).toLocaleString('ru-RU'):'Без известного срока'}</span><span className="muted">{row.stale?'Предыдущая копия; требуется повторная проверка.':obligationNeedsMe(row,now)?'Ожидает моего действия':'Ответ уже есть, действие недоступно или приём завершён.'}</span><button className="btn quiet" disabled={busy||row.stale} onClick={()=>void open(row)}>Открыть этот объект</button></article>)}</details>;
}
