import { useEffect, useRef, useState } from "react";
import { Sheet } from "./sheet";

function clock(seconds:number){const value=Math.max(0,Math.floor(seconds));return `${Math.floor(value/60)}:${String(value%60).padStart(2,"0")}`;}
export function MediaPlayer({src,kind="voice",knownDuration=0}:{src:string;kind?:"voice"|"circle"|"video";knownDuration?:number}){
  const player=useRef<HTMLMediaElement|null>(null);
  const [playing,setPlaying]=useState(false);const [error,setError]=useState(false);
  const [duration,setDuration]=useState(knownDuration/1000);const [position,setPosition]=useState(0);const [speed,setSpeed]=useState(1);
  useEffect(()=>{const node=player.current;setError(false);setPlaying(false);setPosition(0);setDuration(knownDuration/1000);return()=>node?.pause();},[src]);
  const events={onPlay:()=>setPlaying(true),onPause:()=>setPlaying(false),onEnded:()=>setPlaying(false),onError:()=>{setError(true);setPlaying(false);},onTimeUpdate:()=>setPosition(player.current?.currentTime||0),onLoadedMetadata:()=>{const value=player.current?.duration;if(value&&Number.isFinite(value))setDuration(value);}};
  function play(){const node=player.current;if(!node)return;if(error){setError(false);node.load();}if(playing)node.pause();else void node.play().catch(reason=>{if(reason?.name!=="AbortError")setError(true);setPlaying(false);});}
  function seek(value:number){const node=player.current;if(node&&Number.isFinite(duration)&&duration>0){node.currentTime=Math.max(0,Math.min(duration,value));setPosition(node.currentTime);}}
  return <div className="stack media-player">{kind==="voice"?<audio ref={node=>{player.current=node;}} src={src} preload="metadata" {...events}/>:<video ref={node=>{player.current=node;}} src={src} preload="metadata" playsInline className="group-video" style={kind==="circle"?{width:220,maxWidth:"100%",aspectRatio:"1",objectFit:"cover",borderRadius:"50%"}:undefined} {...events}/>}<div className="row"><button className="btn" onClick={play}>{error?"Повторить воспроизведение":playing?"Пауза":"Воспроизвести"}</button><span className="muted">{clock(position)} / {duration>0?clock(duration):"—"}</span></div>{error&&<p role="status">Не удалось воспроизвести запись. Можно повторить попытку.</p>}<input type="range" aria-label="Позиция воспроизведения" min={0} max={duration>0?duration:1} step={0.1} value={Math.min(position,duration||0)} disabled={!duration||error} onChange={event=>seek(Number(event.target.value))}/><div className="row"><button className="btn quiet" disabled={!duration||position===0} onClick={()=>seek(position-10)}>−10 с</button><button className="btn quiet" disabled={!duration||position>=duration} onClick={()=>seek(position+10)}>+10 с</button><label className="field">Скорость<select value={speed} onChange={event=>{const value=Number(event.target.value);setSpeed(value);if(player.current)player.current.playbackRate=value;}}>{[1,1.25,1.5,2].map(value=><option key={value} value={value}>{String(value).replace(".",",")}×</option>)}</select></label></div></div>;
}
export function PhotoViewer({src,alt="Фото"}:{src:string;alt?:string}){
  const [open,setOpen]=useState(false);const [zoom,setZoom]=useState(1);const [failed,setFailed]=useState(false);const [retry,setRetry]=useState(0);
  return <><button className="btn quiet photo-open" type="button" aria-label="Открыть фото" onClick={()=>{setOpen(true);setZoom(1);}}><img src={src} alt={alt} loading="lazy"/></button>{open&&<Sheet title={alt} onClose={()=>setOpen(false)}><div className="stack"><div className="row"><button className="btn" disabled={zoom<=1} onClick={()=>setZoom(value=>Math.max(1,value-.5))} aria-label="Уменьшить фото">−</button><span>{Math.round(zoom*100)}%</span><button className="btn" disabled={zoom>=4} onClick={()=>setZoom(value=>Math.min(4,value+.5))} aria-label="Увеличить фото">+</button><button className="btn quiet" onClick={()=>setZoom(1)}>Вписать фото</button></div>{failed?<div role="status">Фото не открылось.<button className="btn" onClick={()=>{setFailed(false);setRetry(value=>value+1);}}>Повторить</button></div>:<div style={{overflow:"auto",maxHeight:"65dvh",width:"100%"}} tabIndex={0} aria-label="Фото, прокручивайте для перемещения"><img key={retry} src={src} alt={alt} style={{width:`${zoom*100}%`,maxWidth:"none",height:"auto"}} onError={()=>setFailed(true)}/></div>}</div></Sheet>}</>;
}
