import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import * as api from './api';
import {useApp} from './store';
import {useBrowseValue} from './ux300-controls';
import {assessmentPlan,exactLessonIndex,rawLessonKey,roomActivity,WeekChanges,subgroupCandidate,technicalSummary} from './study-discovery';
import {actualStudyWeek,compareStudyWeeks} from './study-overviews';
import {addDays,isoDay,lessonsOn} from './parity';
import {absoluteDate,localDay} from './planner';
import {subgroupIndex,visibleLessons} from './subgroups';
import {parseCampusGraph,campusPlaces,type CampusGraph,type CampusNode} from './campus-routing';
import type {Lesson,PublicMapAsset} from './types';

export const studyOwner=(app:ReturnType<typeof useApp>)=>JSON.stringify([app.session?.authenticated,app.session?.user?.userId,app.session?.familyId,app.groupId]);
function useExactLesson(){const app=useApp(),navigate=useNavigate(),live=useRef(app);live.current=app;const owner=studyOwner(app);const [note,setNote]=useState('');
 useEffect(()=>setNote(''),[owner]);
 return {note,open:(day:string,lesson:Lesson)=>{const current=live.current;if(studyOwner(current)!==owner)return;const date=localDay(day),payload=api.readCache().lessons[current.groupId];const key=rawLessonKey(lesson);
  if(!date||!payload||day<payload.period.start.slice(0,10)||exactLessonIndex(lessonsOn(visibleLessons(payload.lessons,current.subgroups[current.groupId]||{}),date,payload.period.start,payload.period.weekCount,current.invert),key)<0){setNote('Пара изменилась или больше не видна в выбранной подгруппе. Обновите список.');return;}
  current.setDate(date);navigate('/schedule?'+new URLSearchParams({date:day,group:current.groupId,rawTarget:key}));}};
}
function Slot({day,lesson,onOpen}:{day:string;lesson:Lesson;onOpen?:()=>void}){return <article className="card stack"><b>{localDay(day)?absoluteDate(localDay(day)!):day} · {lesson.timeStart}–{lesson.timeEnd}</b><span>{lesson.subjectRaw} · {lesson.typeRaw}</span><span className="muted">{lesson.teacherRaw||'Преподаватель не указан'} · {lesson.classroomRaw||'Аудитория не указана'}</span>{onOpen&&<button className="btn quiet" onClick={onOpen}>Открыть эту пару</button>}</article>;}
export function AssessmentPlanner(){const app=useApp();const [start,setStart]=useBrowseValue('assessment-start',isoDay(new Date()));const date=localDay(start);const period=api.readCache().lessons[app.groupId]?.period;const lessons=visibleLessons(app.lessons,app.subgroups[app.groupId]||{});const result=date?assessmentPlan(lessons,date,period,app.invert,app.timetableAvailable):null;const jump=useExactLesson();
 return <details className="card stack"><summary>Предстоящие зачёты и экзамены</summary><p className="muted">Ближайшее вхождение каждого исходного слота в течение 28 дней по сохранённому расписанию и выбранной подгруппе. Это не отдельный официальный календарь сессии.</p><label className="field">Дата начала<input type="date" value={start} onChange={event=>setStart(event.target.value)}/></label>{date&&<p>{start} — {isoDay(addDays(date,27))}</p>}{result?.unknownDays!==0&&<p role="status">Дней без известных данных: {result?.unknownDays??28}. Отсутствие данных не означает отсутствие оценок.</p>}{result&&result.unknownDays<28&&!result.rows.length&&<p>В известной части периода зачёты и экзамены не найдены.</p>}{jump.note&&<p role="status">{jump.note}</p>}{result?.rows.map((row,index)=><Slot key={index} {...row} onOpen={()=>jump.open(row.day,row.lesson)}/>)}</details>;
}
export function RecentWeekChanges(){const app=useApp();const cache=api.readCache().lessons[app.groupId];const shown=visibleLessons(app.lessons,app.subgroups[app.groupId]||{});const days=actualStudyWeek(shown,app.date,cache?.period,app.invert,app.timetableAvailable);const scope=JSON.stringify([studyOwner(app),isoDay(days[0].date),cache?.period.start,cache?.period.weekCount,app.invert]);const journal=useRef(new WeekChanges());const [result,setResult]=useState<ReturnType<typeof compareStudyWeeks>|null>(null);const jump=useExactLesson();const selection=JSON.stringify([app.invert,app.subgroups[app.groupId]||{}]);
 useEffect(()=>{setResult(journal.current.observe(scope,days,String(app.timetableRevision),selection,app.timetableLoading,app.timetableFailed));},[scope,app.timetableRevision,app.lessons,selection,app.timetableLoading,app.timetableFailed]);
 return <details className="card stack"><summary>Что изменилось на этой неделе</summary><p className="muted">Сравнение двух последовательных копий этой недели после обновления расписания или выбора подгруппы. Предыдущая версия хранится, пока открыт этот экран.</p><button className="btn" disabled={app.timetableLoading} onClick={app.refresh}>{app.timetableLoading?'Обновляем…':'Обновить расписание'}</button>{app.timetableFailed&&<p role="status">Обновление не удалось. Новое сравнение не построено; сохранённая копия осталась.</p>}{!result?<p>После следующего успешного обновления появится сравнение с текущей неделей.</p>:!result.known?<p>Для сравнения нужны данные всех семи дней.</p>:<><p role="status">Добавлено: {result.added.length} · убрано: {result.removed.length}</p>{!result.added.length&&!result.removed.length&&<p>На этой неделе изменений нет.</p>}{result.removed.length>0&&<h3>Убрано из недели</h3>}{result.removed.map((row,index)=><Slot key={'r'+index} day={isoDay(row.date)} lesson={row.lesson}/>)}{result.added.length>0&&<h3>Добавлено в неделю</h3>}{result.added.map((row,index)=><Slot key={'a'+index} day={isoDay(row.date)} lesson={row.lesson} onOpen={()=>jump.open(isoDay(row.date),row.lesson)}/>)}</>}{jump.note&&<p role="status">{jump.note}</p>}</details>;
}
export function SubgroupPreview(){const app=useApp(),live=useRef(app);live.current=app;const [candidate,setCandidate]=useState<{stream:string;option:string;stamp:string}|null>(null),[note,setNote]=useState('');const choices=app.subgroups[app.groupId]||{},period=api.readCache().lessons[app.groupId]?.period;const stamp=(value:typeof app)=>JSON.stringify([studyOwner(value),isoDay(value.date),value.invert,value.subgroups[value.groupId]||{},value.lessons,api.readCache().lessons[value.groupId]?.period]);const currentStamp=stamp(app);const before=actualStudyWeek(visibleLessons(app.lessons,choices),app.date,period,app.invert,app.timetableAvailable);const after=candidate?actualStudyWeek(visibleLessons(app.lessons,subgroupCandidate(choices,candidate.stream,candidate.option)),app.date,period,app.invert,app.timetableAvailable):[];const diff=compareStudyWeeks(before,after),fresh=candidate?.stamp===currentStamp;
 return <details className="card stack"><summary>Сравнить варианты подгруппы</summary><p>Неделя {isoDay(before[0].date)} — {isoDay(before[6].date)}. Предпросмотр не меняет сохранённый выбор.</p>{subgroupIndex(app.lessons).streams.map(stream=><section className="stack" key={stream.id}><h3>{stream.title}</h3>{stream.options.map(option=><button className="btn quiet" key={option.id} onClick={()=>{setCandidate({stream:stream.id,option:option.id,stamp:currentStamp});setNote('');}}>{choices[stream.id]===option.id?'Посмотреть без ограничения: ':'Посмотреть вариант: '}{option.label}</button>)}</section>)}{!subgroupIndex(app.lessons).streams.length&&<p>В текущей копии нет распознанных вариантов подгрупп.</p>}{candidate&&<><p role="status">{!fresh?'Данные изменились. Выберите вариант заново.':!diff.known?'Неделя не полностью известна. Применение недоступно.':`Добавится: ${diff.added.length} · исчезнет: ${diff.removed.length}`}</p>{fresh&&diff.known&&<>{diff.removed.length>0&&<h3>Перестанут показываться</h3>}{diff.removed.map((row,i)=><Slot key={'r'+i} day={isoDay(row.date)} lesson={row.lesson}/>)}{diff.added.length>0&&<h3>Будут показываться</h3>}{diff.added.map((row,i)=><Slot key={'a'+i} day={isoDay(row.date)} lesson={row.lesson}/>)}</>}<button className="btn primary" disabled={!fresh||!diff.known} onClick={()=>{const value=live.current;if(stamp(value)!==candidate.stamp||!subgroupIndex(value.lessons).streams.some(stream=>stream.id===candidate.stream&&stream.options.some(option=>option.id===candidate.option))){setNote('Расписание или профиль изменились. Повторите предпросмотр.');return;}try{value.pickSubgroup(candidate.stream,candidate.option);setCandidate(null);setNote('Выбор применён. Его можно отменить в расписании.');}catch{setNote('Выбор не сохранился. Повторите после обновления данных.');}}}>Применить показанный вариант</button></>}{note&&<p role="status">{note}</p>}</details>;
}
export function RoomActivity({asset,onMark}:{asset:PublicMapAsset;onMark:(node:CampusNode)=>void}){const app=useApp();const [open,setOpen]=useState(false),[graph,setGraph]=useState<CampusGraph|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[date,setDate]=useState(isoDay(app.date));const [,reread]=useState(0);
 useEffect(()=>{if(!open)return;let active=true;const controller=new AbortController();setError('');setGraph(null);void(async()=>{const url=new URL(asset.url,window.location.origin);if(url.origin!==window.location.origin||!url.pathname.startsWith('/api/v1/maps/assets/'))throw Error();const response=await fetch(url,{credentials:'same-origin',signal:controller.signal});if(!response.ok)throw Error();const bytes=await response.arrayBuffer();if(bytes.byteLength!==asset.bytes)throw Error();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(hash.toLowerCase()!==asset.sha256.toLowerCase())throw Error();const value=parseCampusGraph(JSON.parse(new TextDecoder().decode(bytes)));if(active)setGraph(value);})().catch(reason=>{if(active&&reason?.name!=='AbortError')setError('Список помещений недоступен. Планы карты остаются доступными.');});return()=>{active=false;controller.abort();};},[open,asset.url,asset.sha256,asset.bytes,retry]);
 const cache=api.readCache(),day=localDay(date),node=graph?.nodes.find(node=>node.id===selected&&node.kind==='room');const result=graph&&day&&node?roomActivity(graph,node.id,day,app.catalog?.groups||cache.groups?.groups||[],cache.lessons,app.invert):null;const places=graph?campusPlaces(graph,query).filter(node=>node.kind==='room'):[];
 return <section className="card stack"><button className="btn" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>Занятия в аудитории по известным копиям</button>{open&&<><p className="muted">Все подгруппы известных локальных копий. Новые расписания групп не скачиваются. Список не доказывает, что аудитория свободна.</p>{error?<p role="status">{error}<button className="btn" onClick={()=>setRetry(n=>n+1)}>Повторить</button></p>:!graph?<p role="status">Загружаем помещения…</p>:<><label className="field">Найти аудиторию<input value={query} onChange={event=>setQuery(event.target.value)}/></label><label className="field">Помещение<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Выберите аудиторию</option>{node&&!places.some(row=>row.id===node.id)&&<option value={node.id}>{node.label||node.room} · {node.building}</option>}{places.map(place=><option key={place.id} value={place.id}>{place.label||place.room} · {place.building}, {place.floor} этаж</option>)}</select></label><label className="field">Дата<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button className="btn quiet" onClick={()=>reread(n=>n+1)}>Перечитать сохранённые копии</button>{node&&<button className="btn" onClick={()=>onMark(node)}>Показать выбранную аудиторию</button>}{result&&<><p role="status">Проверено групп: {result.checked} из {result.known} известных. Не сопоставлено пар: {result.unmapped}.</p>{!result.rows.length&&<p>Среди проверенных копий занятий не найдено.</p>}{result.rows.map((row,i)=><article className="card stack" key={i}><b>{row.group.name} · {row.lesson.timeStart}–{row.lesson.timeEnd}</b><span>{row.lesson.subjectRaw} · {row.lesson.teacherRaw}</span><span className="muted">Копия: {row.fetchedAt?new Date(row.fetchedAt).toLocaleString('ru-RU'):'дата неизвестна'}. Текущая личная группа не меняется.</span><button className="btn quiet" onClick={()=>onMark(node!)}>Показать место занятия</button></article>)}</>}</>}</>}</section>;
}
export function SupportDiagnostics(){const app=useApp(),live=useRef(app);live.current=app;const owner=studyOwner(app);const epoch=useRef(0);const [text,setText]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState('');useEffect(()=>{setText('');setNote('');setBusy(false);return()=>{epoch.current++;};},[owner]);
 async function prepare(){const generation=++epoch.current,auth=api.authGeneration();const current=()=>generation===epoch.current&&studyOwner(live.current)===owner&&api.authGeneration()===auth;setBusy(true);setText('');setNote('');let maps:number|null=null;try{maps=(await api.loadMaps()).maps.length;}catch{}if(!current())return;const value=live.current,cache=api.readCache(),fetched=Date.parse(cache.lessons[value.groupId]?.meta?.fetchedAt||'');const scripts=Array.from(document.scripts).map(script=>script.src);const version=scripts.map(src=>src.match(/\/index-([a-zA-Z0-9_-]+)\.js(?:\?|$)/)?.[1]).find(Boolean)||'dev';setText(technicalSummary({version,available:value.timetableAvailable,cacheGroups:new Set(Object.values(cache.lessons).map(row=>row.group?.id).filter(Boolean)).size,cacheAgeDays:Number.isFinite(fetched)?Math.max(0,Math.floor((Date.now()-fetched)/86400000)):null,maps,pending:value.privateHomework.pending.length,conflicts:value.privateHomework.pending.filter(row=>row.conflict!==undefined).length}));setBusy(false);}
 return <article className="card stack"><h2>Техническая сводка для поддержки</h2><p className="muted">Только версия, доступность копий и числовые показатели. Без имён, групп, путей, текста заданий, переписки и токенов. Ничего не отправляется в поддержку автоматически.</p><button className="btn" disabled={busy} onClick={()=>void prepare()}>{busy?'Проверяем каталог карт…':'Подготовить предпросмотр'}</button>{text&&<><pre className="technical-summary" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{text}</pre><button className="btn" onClick={()=>{if(studyOwner(live.current)!==owner)return;const token=epoch.current;void navigator.clipboard.writeText(text).then(()=>{if(epoch.current===token)setNote('Техническая сводка скопирована.');}).catch(()=>{if(epoch.current===token)setNote('Не удалось скопировать. Выделите текст предпросмотра вручную.');});}}>Скопировать эту сводку</button></>}{note&&<p role="status">{note}</p>}</article>;
}
