import { useEffect, useRef, useState } from "react";
import { createCalendarExport } from "./calendar-export";
import { scheduleCalendarEntries, schedulePlainText, type ExportDay } from "./schedule-export";
export function TimetableExportTools({days,groupId,groupName}:{days:ExportDay[];groupId:string;groupName:string}){
 const [busy,setBusy]=useState(false);const[note,setNote]=useState("");const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const scope=JSON.stringify([groupId,days]);const live=useRef(scope);live.current=scope;
 async function download(){if(busy)return;const captured=scope;setBusy(true);setNote("");try{const result=await createCalendarExport(scheduleCalendarEntries(days,groupId),`Расписание ${groupName}`);if(!mounted.current||live.current!==captured)return;if(!result.eventCount){setNote("Нет занятий с корректной датой и временем для календаря.");return;}const url=URL.createObjectURL(new Blob([result.content],{type:"text/calendar;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="voenmeh-schedule.ics";anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),60000);setNote(`Подготовлено событий: ${result.eventCount}${result.skippedCount?` · пропущено некорректных: ${result.skippedCount}`:""}. Это снимок выбранного расписания, без автоматических обновлений.`);}catch{if(mounted.current)setNote("Файл не подготовлен. Расписание осталось доступно.");}finally{if(mounted.current)setBusy(false);}}
 return <div className="stack"><div className="row"><button className="btn quiet" disabled={!groupId||busy} onClick={()=>void download()}>{busy?"Готовим календарь…":"Скачать календарь .ics"}</button><button className="btn quiet" disabled={!groupId} onClick={()=>void navigator.clipboard.writeText(schedulePlainText(days,groupName)).then(()=>{if(mounted.current)setNote("Текст выбранного расписания скопирован.");}).catch(()=>{if(mounted.current)setNote("Буфер обмена недоступен. Можно выделить текст расписания вручную.");})}>Скопировать расписание</button></div>{note&&<p role="status">{note}</p>}</div>;
}
