import * as workflowRules from "./ux300.ts";
import assert from "node:assert/strict";
import { test } from "node:test";
import { readFile } from "node:fs/promises";
import { runInNewContext } from "node:vm";
import ts from "typescript";
import * as revocation from "./draft-revocation.ts";
import * as authority from "./topic-authority.ts";
import * as pending from "./creation-pending.ts";
import * as policy from "./topic-policy.ts";
import * as channels from "./channels.ts";
import * as browse from "./groupBrowse.ts";
import { timetableSubjects } from "./community-timetable.ts";
const compile=(source:string,jsx=false)=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:jsx?ts.JsxEmit.ReactJSX:undefined}}).outputText;
const code=compile(await readFile(new URL("./topics.tsx",import.meta.url),"utf8"),true),draftCode=compile(await readFile(new URL("./draft-store.ts",import.meta.url),"utf8"));
const base={topicId:"t",title:"Тема",icon:"🧪",kind:"chat",template:"subject",description:"Описание",accent:"purple",pinned:false,writePolicy:"managers",categoryId:null,position:3,subject:"Математика",revision:7,permissions:["read"],supported:true,lastBody:null,lastAuthor:null,lastAt:null,unread:0,canPost:false,canDelete:false,activeBallots:0};
const nodes=(tree:any):any[]=>Array.isArray(tree)?tree.flatMap(nodes):tree&&typeof tree==="object"?[tree,...nodes(tree.props?.children)]:[];
const text=(tree:any):string=>Array.isArray(tree)?tree.map(text).join(" "):tree&&typeof tree==="object"?text(tree.props?.children):typeof tree==="string"||typeof tree==="number"?String(tree):"";
const button=(tree:any,label:string)=>nodes(tree).find(node=>node.type==="button"&&text(node)===label);
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test("actual disposed GroupTopics archive403 cannot purge newly authorized same-owner/community draft",async()=>{
 const session=new Map<string,string>();let hold=false,rejectOld:(error:Error)=>void=()=>{};
 const first=harness({session,topics:[{...base,topicId:"A",title:"Authorized A"}],api:{archivedTopics:async()=>hold?new Promise((_,reject)=>{rejectOld=reject;}):{topics:[],canManageChannels:false}}});
 await first.boot();hold=true;first.tick();await settle();first.dispose();
 const second=harness({session,topics:[{...base,topicId:"A",title:"Authorized A"}]});await second.boot();
 const key="zapara.draft.v2:owner:c:A:material-link:";session.set(key,JSON.stringify("new authorized draft A"));
 rejectOld(new Error("403"));await settle();assert.equal(session.get(key),JSON.stringify("new authorized draft A"));assert.match(text(second.render()),/Authorized A/);
 second.api.archivedTopics=async()=>{throw new Error("403");};second.tick();await settle();assert.equal(session.has(key),false);second.dispose();
});
function harness(options:{mine?:string[];topics?:any[];rules?:any[];categories?:any[];legacy?:boolean;local?:Map<string,string>;session?:Map<string,string>;owner?:string;community?:string;api?:any}={}){
    const states:any[]=[],effects:(()=>any)[]=[],cleanups:(()=>void)[]=[],timers:(()=>void)[]=[],calls:any[]=[],opened:any[]=[],errors:string[]=[];let index=0,first=true;const local=options.local??new Map(),session=options.session??new Map(),listeners=new Map<string,Set<(event:any)=>void>>();
    const react={useState:(initial:any)=>{const slot=index++;if(!(slot in states))states[slot]=typeof initial==="function"?initial():initial;return[states[slot],(value:any)=>{states[slot]=typeof value==="function"?value(states[slot]):value;}];},useRef:(initial:any)=>{const slot=index++;if(!(slot in states))states[slot]={current:initial};return states[slot];},useEffect:(effect:any)=>{if(first)effects.push(effect);}};
    const storage=(memory:Map<string,string>)=>({get length(){return memory.size;},key:(index:number)=>[...memory.keys()][index]??null,getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)});
    const window={setInterval:(fn:()=>void)=>(timers.push(fn),timers.length),clearInterval:()=>{},confirm:()=>true,dispatchEvent:(event:any)=>{listeners.get(event.type)?.forEach(listener=>listener(event));return true;},addEventListener:(type:string,fn:any)=>{if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type)!.add(fn);},removeEventListener:(type:string,fn:any)=>listeners.get(type)?.delete(fn)};
    const globals={Error,window,localStorage:storage(local),sessionStorage:storage(session),CustomEvent:class{type:string;detail:any;constructor(type:string,init:any){this.type=type;this.detail=init.detail;}}};
    const draftContext={...globals,exports:{} as any,require:(id:string)=>id==="react"?react:revocation};runInNewContext(draftCode,draftContext);
    const topics=options.topics??[{...base}],desk={headman:false,mine:options.mine??[],roles:[{roleId:"r1",name:"Роль 1"},{roleId:"r2",name:"Роль 2"}],grants:[],powers:[],applicants:[]};
    const space={topics,desk,categories:options.categories??[],capabilities:{maxTopics:24,powers:["read","post","media","channels","access","pin","moderate","joins","exclude","roles","grants"],templates:["chat","polls","subject"]}};
    const api={archivedTopics:async()=>({topics:[],canManageChannels:false}),groupSpace:async()=>{if(options.legacy)throw new Error("404");return space;},groupDesk:async()=>desk,topics:async()=>({topics,canManageChannels:desk.mine.includes("channels")}),groupHome:async()=>({classmates:[]}),topicAccess:async()=>({topicId:"t",revision:7,rules:options.rules??[{roleId:null,power:"read",state:"inherit"}]}),previewTopicAccess:async(...args:any[])=>{calls.push({action:"preview",args:JSON.parse(JSON.stringify(args))});return{topicId:"t",revision:7,affectedCount:0,beforeReaders:[],afterReaders:[],participants:[]};},saveTopicAccess:async(...args:any[])=>{calls.push({action:"access-save",args:JSON.parse(JSON.stringify(args))});return space;},renameTopic:async(...args:any[])=>{calls.push({action:"rename",args:JSON.parse(JSON.stringify(args))});return {topics};},archiveTopic:async(...args:any[])=>{calls.push({action:"archive",args});return space;},createTopic:async(...args:any[])=>{calls.push({action:"create",args:JSON.parse(JSON.stringify(args))});return{topics};}};
    Object.assign(api,options.api??{});
    const jsx=(type:any,props:any)=>({type,props});const modules:any={react,"react/jsx-runtime":{jsx,jsxs:jsx,Fragment:"fragment"},"./api":api,"./ux300":workflowRules,"./ux300-controls":{SearchField:()=>null},"./topic-policy":policy,"./draft-revocation":revocation,"./topic-authority":authority,"./creation-pending":{...pending,usePendingCreation:(key:string)=>{const [value,set]=react.useState(()=>pending.hasPendingCreation(key));react.useEffect(()=>pending.subscribeCreation(key,()=>set(pending.hasPendingCreation(key))));return value;}},"./draft-store":draftContext.exports,"./store":{useApp:()=>({session:{user:{userId:options.owner??"owner"}}})},"./channels":channels,"./groupBrowse":browse,"./icons":{Icon:()=>null},"./community-timetable":{timetableSubjects},"./use-community-timetable":{useCommunityTimetable:()=>({payload:{lessons:[{subjectRaw:"Математика"}]},loading:false,error:""})}};
    const context={...globals,exports:{} as any,require:(id:string)=>modules[id]};runInNewContext(code,context);
    const render=()=>{index=0;const tree=context.exports.GroupTopics({communityId:options.community??"c",groupName:"Б162",onOpen:(...args:any[])=>opened.push(args),onError:(error:string)=>errors.push(error)});first=false;return tree;};
    return{api,calls,opened,errors,local,session,render,tick(){timers.forEach(timer=>timer());},dispose(){cleanups.forEach(cleanup=>cleanup());},async boot(){render();effects.forEach(effect=>{const cleanup=effect();if(typeof cleanup==="function")cleanups.push(cleanup);});await settle();return render();}};
}
test("actual delegated topic channels/access actions work without global powers; explicit topic denial hides them",async()=>{
    const channel=harness({topics:[{...base,permissions:["read","channels"]}]});let tree=await channel.boot();assert.equal(button(tree,"Управление"),undefined);button(tree,"Настройки").props.onClick();tree=channel.render();assert.ok(button(tree,"Сохранить"));assert.equal(button(tree,"Доступ к каналу"),undefined);assert.equal(nodes(tree).find(node=>node.type==="select"&&node.props.value==="managers").props.disabled,true);nodes(tree).find(node=>node.type==="input"&&node.props.value==="Тема").props.onChange({target:{value:"Новое имя"}});tree=channel.render();nodes(tree).find(node=>node.type==="form").props.onSubmit({preventDefault(){}});await settle();assert.equal(channel.calls[0].action,"rename");assert.equal(channel.calls[0].args[1],"t");assert.equal(channel.calls[0].args[5].expectedRevision,7);assert.equal(channel.calls[0].args[5].writePolicy,"managers");
    const access=harness({topics:[{...base,permissions:["read","access"]}]});tree=await access.boot();assert.equal(button(tree,"Настройки"),undefined);button(tree,"Доступ").props.onClick();await settle();tree=access.render();assert.ok(button(tree,"Проверить последствия"));assert.equal(button(tree,"Сохранить"),undefined);assert.ok(button(tree,"Закрыть доступ"));
    const denied=harness({mine:["channels","access","pin"],topics:[{...base,permissions:["read"]}]});tree=await denied.boot();assert.equal(button(tree,"Настройки"),undefined);assert.equal(button(tree,"Доступ"),undefined);assert.equal(button(tree,"Закрепить"),undefined);assert.ok(button(tree,"Управление"));
});
test("actual pin-only action sends unchanged metadata with just pinned toggled",async()=>{const app=harness({topics:[{...base,permissions:["read","pin"]}]});const tree=await app.boot();assert.equal(button(tree,"Настройки"),undefined);assert.equal(button(tree,"Доступ"),undefined);button(tree,"Закрепить").props.onClick();await settle();assert.deepEqual(app.calls[0],{action:"rename",args:["c","t","Тема","🧪","chat",{description:"Описание",accent:"purple",pinned:true,writePolicy:"managers",template:"subject",categoryId:null,position:3,subject:"Математика",expectedRevision:7}]});});
test("actual Simple ACL controls clean inert fields, preserve other powers and preview/save selected-role presets",async()=>{const app=harness({topics:[{...base,permissions:["read","access"]}],rules:[{roleId:null,power:"roles",state:"allow"},{roleId:null,power:"joins",state:"deny"},{roleId:"r2",power:"media",state:"allow"},{roleId:null,power:"read",state:"inherit"}]});let tree=await app.boot();button(tree,"Доступ").props.onClick();await settle();tree=app.render();assert.equal(nodes(tree).some(node=>node.type==="select"&&/Менять роли:|Принимать заявки:/.test(node.props["aria-label"]??"")),false);nodes(tree).find(node=>node.type==="select"&&node.props["aria-label"]==="Кто видит канал").props.onChange({target:{value:"selected"}});tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props["aria-label"]==="Кто видит канал: Роль 1").props.onChange({target:{checked:true}});tree=app.render();nodes(tree).find(node=>node.type==="select"&&node.props["aria-label"]==="Кто публикует").props.onChange({target:{value:"headman"}});tree=app.render();button(tree,"Проверить последствия").props.onClick();await settle();tree=app.render();button(tree,"Сохранить проверенный доступ").props.onClick();await settle();const rules=[{roleId:"r2",power:"media",state:"allow"},{roleId:null,power:"read",state:"deny"},{roleId:"r1",power:"read",state:"allow"},{roleId:null,power:"post",state:"deny"}];assert.deepEqual(app.calls.find(call=>call.action==="preview")!.args[2],rules);assert.deepEqual(app.calls.find(call=>call.action==="access-save")!.args[2],rules);});
test("actual category collapse persists independently, search exposes matches, empty categories stay absent",async()=>{const local=new Map<string,string>();const topics=[{...base,topicId:"p",title:"Закреплённый",categoryId:"c1",pinned:true,position:100},{...base,topicId:"u",title:"Другое",categoryId:"c1",position:0},{...base,topicId:"other",title:"Вторая тема",categoryId:"c2"}];const options={local,topics,categories:[{categoryId:"c1",title:"Первая",position:0},{categoryId:"c2",title:"Вторая",position:1},{categoryId:"empty",title:"Пустая",position:2}]};const app=harness(options);let tree=await app.boot();assert.equal(button(tree,"Пустая"),undefined);assert.match(text(nodes(tree).filter(node=>node.props?.className==="topic-open")[0]),/Закреплённый/);button(tree,"Первая").props.onClick();tree=app.render();assert.equal(button(tree,"Первая").props["aria-expanded"],false);assert.match(text(tree),/Вторая тема/);assert.equal(text(tree).includes("Закреплённый"),false);nodes(tree).find(node=>node.type==="input"&&node.props.type==="search").props.onChange({target:{value:"Другое"}});tree=app.render();assert.match(text(tree),/Другое/);assert.equal(button(tree,"Первая").props["aria-expanded"],true);nodes(tree).find(node=>node.type==="input"&&node.props.type==="search").props.onChange({target:{value:""}});tree=app.render();assert.equal(button(tree,"Первая").props["aria-expanded"],false);tree=await harness(options).boot();assert.equal(button(tree,"Первая").props["aria-expanded"],false);assert.equal(button(tree,"Вторая").props["aria-expanded"],true);});
test("actual private creation sends one atomic request with initial ACL and acknowledges a filtered response",async()=>{
    const app=harness({mine:["channels","access"]});let tree=await app.boot();button(tree,"Управление").props.onClick();tree=app.render();button(tree,"Создать канал").props.onClick();tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props.required&&node.props.maxLength===40).props.onChange({target:{value:"Закрытый канал"}});tree=app.render();nodes(tree).find(node=>node.type==="select"&&node.props["aria-label"]==="Кто видит новый канал").props.onChange({target:{value:"selected"}});tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props["aria-label"]==="Кто видит новый канал: Роль 1").props.onChange({target:{checked:true}});tree=app.render();nodes(tree).find(node=>node.type==="select"&&node.props["aria-label"]==="Кто публикует в новом канале").props.onChange({target:{value:"headman"}});tree=app.render();nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании")).props.onSubmit({preventDefault(){}});await settle();tree=app.render();assert.equal(app.errors.length,0);assert.equal(app.calls.length,1);assert.equal(app.calls[0].action,"create");assert.deepEqual(app.calls[0].args[4].initialAccessRules,[{roleId:null,power:"read",state:"deny"},{roleId:"r1",power:"read",state:"allow"},{roleId:null,power:"post",state:"deny"}]);assert.equal(text(tree).includes("Просмотр и публикация при создании"),false);assert.equal([...app.session.keys()].some(key=>key.includes("topic-create")),false);
});
test("actual creation draft restores fields and role presets across remount and blocks legacy/public fallback",async()=>{
    const session=new Map<string,string>();const options={mine:["channels","access"],session};const app=harness(options);let tree=await app.boot();button(tree,"Управление").props.onClick();tree=app.render();button(tree,"Создать канал").props.onClick();tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props.required&&node.props.maxLength===40).props.onChange({target:{value:"Сохранённый черновик"}});tree=app.render();nodes(tree).find(node=>node.type==="select"&&node.props["aria-label"]==="Кто видит новый канал").props.onChange({target:{value:"selected"}});tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props["aria-label"]==="Кто видит новый канал: Роль 2").props.onChange({target:{checked:true}});
    const restored=harness(options);tree=await restored.boot();button(tree,"Управление").props.onClick();tree=restored.render();button(tree,"Создать канал").props.onClick();tree=restored.render();assert.ok(nodes(tree).some(node=>node.type==="input"&&node.props.value==="Сохранённый черновик"));assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто видит новый канал: Роль 2").props.checked,true);
    for(const legacy of [false,true]){const blocked=harness({mine:["channels"],session,legacy});tree=await blocked.boot();button(tree,"Управление").props.onClick();tree=blocked.render();button(tree,"Создать канал").props.onClick();tree=blocked.render();assert.equal(button(tree,"Сохранить").props.disabled,true);nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании")).props.onSubmit({preventDefault(){}});await settle();assert.equal(blocked.calls.some(call=>call.action==="create"),false);assert.ok(blocked.errors.length);}
});
test("default creation omits initial ACL and unknown modern topics have no mutation controls",async()=>{const app=harness({mine:["channels"],topics:[{...base,kind:"future",supported:false,permissions:["read","channels","access","pin"]}]});let tree=await app.boot();assert.equal(button(tree,"Настройки"),undefined);assert.equal(button(tree,"Доступ"),undefined);assert.equal(button(tree,"Закрепить"),undefined);button(tree,"Управление").props.onClick();tree=app.render();button(tree,"Создать канал").props.onClick();tree=app.render();nodes(tree).find(node=>node.type==="input"&&node.props.required&&node.props.maxLength===40).props.onChange({target:{value:"Обычный"}});tree=app.render();assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто видит новый канал").props.disabled,true);nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании")).props.onSubmit({preventDefault(){}});await settle();assert.equal(app.calls[0].action,"create");assert.equal("initialAccessRules" in app.calls[0].args[4],false);});
test("actual post selected mode exposes the first role and preserves an empty selection across creation remount",async()=>{
    const existing=harness({topics:[{...base,permissions:["read","access"]}]});let tree=await existing.boot();button(tree,"Доступ").props.onClick();await settle();tree=existing.render();nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует").props.onChange({target:{value:"selected"}});tree=existing.render();assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует").props.value,"selected");nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует: Роль 1").props.onChange({target:{checked:true}});tree=existing.render();button(tree,"Проверить последствия").props.onClick();await settle();assert.deepEqual(existing.calls.find(call=>call.action==="preview")!.args[2].filter((row:any)=>row.power==="post"),[{roleId:null,power:"post",state:"deny"},{roleId:"r1",power:"post",state:"allow"}]);
    const session=new Map<string,string>();const creator=harness({mine:["channels","access"],session});tree=await creator.boot();button(tree,"Управление").props.onClick();tree=creator.render();button(tree,"Создать канал").props.onClick();tree=creator.render();nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует в новом канале").props.onChange({target:{value:"selected"}});tree=creator.render();assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует в новом канале: Роль 1").props.checked,false);const restored=harness({mine:["channels","access"],session});tree=await restored.boot();button(tree,"Управление").props.onClick();tree=restored.render();button(tree,"Создать канал").props.onClick();tree=restored.render();assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует в новом канале").props.value,"selected");nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует в новом канале: Роль 1").props.onChange({target:{checked:true}});tree=restored.render();assert.equal(nodes(tree).find(node=>node.props?.["aria-label"]==="Кто публикует в новом канале: Роль 1").props.checked,true);
});
test("actual archive/editor snapshots drop A on authoritative refresh and late access/archive replies cannot restore it",async()=>{
 let archived:any[]=[{...base,topicId:"A",title:"Forbidden A",lastBody:"A private body",unread:9,archived:true,permissions:["read","channels","access"]},{...base,topicId:"B",title:"Allowed B",archived:true,permissions:["read","channels","access"]}];let delayed=false,releaseArchive:(value:any)=>void=()=>{},releaseAccess:(value:any)=>void=()=>{};
 const app=harness({topics:[],mine:["channels","access"],api:{archivedTopics:async()=>delayed?new Promise(resolve=>{releaseArchive=resolve;}):{topics:archived,canManageChannels:true}}});let tree=await app.boot();
 button(tree,"Действия").props.onClick();tree=app.render();assert.equal(button(tree,"Действия").props["aria-expanded"],true);
 button(tree,"Архив").props.onClick();await settle();tree=app.render();
 const topicActions=(current:any)=>{const row=nodes(current).find(node=>node.type==="div"&&node.props.className==="topic"&&text(node).includes("Forbidden A"));assert.ok(row,"Archived A remains available before revocation");const details=nodes(row).find(node=>node.type==="details"&&nodes(node).some(child=>child.type==="summary"&&text(child)==="Действия канала"));assert.ok(details,"Channel actions are exposed by their disclosure label");return details;};
 button(topicActions(tree),"Доступ").props.onClick();await settle();tree=app.render();assert.ok(button(tree,"Закрыть доступ"));
 app.api.topicAccess=async()=>new Promise(resolve=>{releaseAccess=resolve;});
 // Start an actual access request from the full editor before read is revoked.
 button(tree,"Закрыть доступ").props.onClick();tree=app.render();button(topicActions(tree),"Настройки").props.onClick();tree=app.render();button(tree,"Доступ к каналу").props.onClick();
 delayed=true;app.tick();await settle();delayed=false;archived=[archived[1]];app.tick();await settle();releaseArchive({topics:[{...base,topicId:"A",title:"Forbidden A",archived:true},archived[0]],canManageChannels:true});releaseAccess({topicId:"A",revision:7,rules:[]});await settle();tree=app.render();assert.equal(text(tree).includes("Forbidden A"),false);assert.equal(text(tree).includes("A private body"),false);assert.match(text(tree),/Allowed B/);assert.equal(button(tree,"Проверить последствия"),undefined);
});
test("actual preview is reconciled and an old preview response cannot reintroduce forbidden A",async()=>{let rows:any[]=[{...base,topicId:"A",title:"Preview private A"},{...base,topicId:"B",title:"Preview allowed B"}],release:(value:any)=>void=()=>{},count=0;const app=harness({mine:["access"],topics:rows,api:{groupSpace:async()=>({topics:rows,categories:[],desk:{headman:false,mine:["access"],roles:[{roleId:"r1",name:"Роль 1"}],grants:[],powers:[],applicants:[]},capabilities:{maxTopics:24,powers:["read","access"],templates:[]}}),previewPermissions:async()=>++count===1?new Promise(resolve=>{release=resolve;}):{topics:rows}}});let tree=await app.boot();nodes(tree).find(node=>node.type==="select"&&node.props.defaultValue==="").props.onChange({target:{value:"r1"}});await settle();rows=[rows[1]];app.tick();await settle();release({topics:[{...base,topicId:"A",title:"Preview private A"},rows[0]]});await settle();tree=app.render();assert.equal(text(tree).includes("Preview private A"),false);assert.match(text(tree),/Preview allowed B/);});
test("actual delayed create survives unmount/remount without duplicate POST and acknowledges hidden201",async()=>{const session=new Map<string,string>();let count=0,release:(value:any)=>void=()=>{};const api={createTopic:async()=>{count++;return new Promise(resolve=>{release=resolve;});}};const first=harness({mine:["channels","access"],session,api});let tree=await first.boot();button(tree,"Управление").props.onClick();tree=first.render();button(tree,"Создать канал").props.onClick();tree=first.render();nodes(tree).find(node=>node.type==="input"&&node.props.required&&node.props.maxLength===40).props.onChange({target:{value:"Pending A"}});tree=first.render();nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании")).props.onSubmit({preventDefault(){}});await settle();first.dispose();const second=harness({mine:["channels","access"],session,api});tree=await second.boot();button(tree,"Управление").props.onClick();tree=second.render();button(tree,"Создать канал").props.onClick();tree=second.render();assert.equal(button(tree,"Сохранить").props.disabled,true);nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании")).props.onSubmit({preventDefault(){}});await settle();assert.equal(count,1);release({topics:[],canManageChannels:true});await settle();assert.equal([...session.keys()].some(key=>key.startsWith("zapara.draft.v2:owner:c:new:")),false);tree=second.render();nodes(tree).find(node=>node.type==="form"&&text(node).includes("Просмотр и публикация при создании"))?.props.onSubmit({preventDefault(){}});await settle();assert.equal(count,1);second.dispose();});
test("actual confirmed membership/account denial purges only captured group/owner scopes and clears private snapshots",async()=>{for(const denial of ["403","401"]){const session=new Map<string,string>();for(const [owner,community,topic] of [["owner","c","A"],["owner","other","B"],["other-owner","c","C"]])session.set(`zapara.draft.v2:${owner}:${community}:${topic}:material-link:`,JSON.stringify("private"));session.set("zapara.homework","guest preserved");const app=harness({mine:["channels","access"],topics:[{...base,topicId:"A",title:"Secret A"}],session});await app.boot();app.api.groupSpace=async()=>{throw new Error(denial);};app.tick();await settle();const tree=app.render();assert.equal(text(tree).includes("Тема"),false);assert.equal(session.has("zapara.draft.v2:owner:c:A:material-link:"),false);assert.equal(session.has("zapara.draft.v2:other-owner:c:C:material-link:"),true);assert.equal(session.get("zapara.homework"),"guest preserved");assert.equal(session.has("zapara.draft.v2:owner:other:B:material-link:"),denial!=="401");app.dispose();}});
test("actual delayed access from old owner/community cannot publish into a changed scope",async()=>{let release:(value:any)=>void=()=>{};const options:any={owner:"owner-A",community:"community-A",mine:["access"],topics:[{...base,topicId:"A",title:"Private owner A",permissions:["read","access"]}],api:{topicAccess:async()=>new Promise(resolve=>{release=resolve;})}};const app=harness(options);let tree=await app.boot();button(tree,"Доступ").props.onClick();await settle();options.owner="owner-B";options.community="community-B";tree=app.render();release({topicId:"A",revision:7,rules:[{roleId:null,power:"read",state:"allow"}]});await settle();tree=app.render();assert.equal(text(tree).includes("Private owner A"),false);assert.equal(button(tree,"Проверить последствия"),undefined);app.dispose();});
