using Npgsql;
using Zapara.Server.Accounts;

namespace Zapara.Server.Social;

internal static class SocialSchema
{
    public static async Task EnsureAsync(AccountsDataSource data, AccountsConfiguration accounts, CancellationToken ct)
    {
        await using var connection = data.CreateConnection();
        await connection.OpenAsync(ct);
        await using (var probe = new NpgsqlCommand("SELECT to_regclass(@name)::text", connection))
        {
            probe.Parameters.AddWithValue("name", accounts.Schema + ".users");
            if (await probe.ExecuteScalarAsync(ct) is null or DBNull or "") return;
        }
        var name = accounts.Schema == "accounts" ? "social" : accounts.Schema + "_social";
        var sql = """
            CREATE SCHEMA IF NOT EXISTS __SCHEMA__;
            CREATE TABLE IF NOT EXISTS __SCHEMA__.codes (
                user_id uuid PRIMARY KEY REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z2-9]{8}$')
            );
            CREATE TABLE IF NOT EXISTS __SCHEMA__.friendships (
                friendship_id uuid PRIMARY KEY,
                requester_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                addressee_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                status text NOT NULL CHECK (status IN ('pending','accepted','declined')),
                pair_key text NOT NULL,
                created_at timestamptz NOT NULL,
                CHECK (requester_id <> addressee_id)
            );
            CREATE UNIQUE INDEX IF NOT EXISTS friendships_open_pair ON __SCHEMA__.friendships(pair_key) WHERE status IN ('pending','accepted');
            CREATE TABLE IF NOT EXISTS __SCHEMA__.conversations (
                conversation_id uuid PRIMARY KEY,
                friendship_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.friendships(friendship_id) ON DELETE CASCADE,
                created_at timestamptz NOT NULL
            );
            CREATE TABLE IF NOT EXISTS __SCHEMA__.messages (
                message_id uuid PRIMARY KEY,
                conversation_id uuid NOT NULL REFERENCES __SCHEMA__.conversations(conversation_id) ON DELETE CASCADE,
                sender_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id),
                kind text NOT NULL CHECK (kind IN ('text','image','file','voice','sticker','circle','card')),
                body text NULL CHECK (body IS NULL OR (char_length(body) BETWEEN 1 AND 2000 AND translate(body, E'\n\t', '') !~ '[[:cntrl:]]')),
                created_at timestamptz NOT NULL,
                message_no bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                reply_to uuid NULL,
                edited_at timestamptz NULL,
                deleted_at timestamptz NULL
            );
            CREATE INDEX IF NOT EXISTS messages_conversation ON __SCHEMA__.messages(conversation_id, message_no);
            CREATE TABLE IF NOT EXISTS __SCHEMA__.attachments (
                attachment_id uuid PRIMARY KEY,
                message_id uuid NOT NULL UNIQUE REFERENCES __SCHEMA__.messages(message_id) ON DELETE CASCADE,
                stored_name text NOT NULL,
                original_name text NOT NULL,
                content_type text NOT NULL,
                byte_count bigint NOT NULL CHECK (byte_count > 0),
                width int NULL,
                height int NULL,
                duration_ms int NULL
            );
            CREATE TABLE IF NOT EXISTS __SCHEMA__.reads (
                conversation_id uuid NOT NULL REFERENCES __SCHEMA__.conversations(conversation_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                last_read_no bigint NOT NULL DEFAULT 0,
                PRIMARY KEY (conversation_id, user_id)
            );
            CREATE TABLE IF NOT EXISTS __SCHEMA__.file_purge (
                stored_name text PRIMARY KEY CHECK (stored_name ~ '^[A-Za-z0-9._-]{8,80}$'),
                created_at timestamptz NOT NULL
            );
            ALTER TABLE __SCHEMA__.messages ADD COLUMN IF NOT EXISTS reply_to uuid;
            ALTER TABLE __SCHEMA__.messages ADD COLUMN IF NOT EXISTS edited_at timestamptz;
            ALTER TABLE __SCHEMA__.messages ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
            ALTER TABLE __SCHEMA__.messages DROP CONSTRAINT IF EXISTS messages_kind_check;
            ALTER TABLE __SCHEMA__.messages ADD CONSTRAINT messages_kind_check CHECK (kind IN ('text','image','file','voice','sticker','circle','card'));
            ALTER TABLE __SCHEMA__.attachments ADD COLUMN IF NOT EXISTS duration_ms integer;
            ALTER TABLE __SCHEMA__.attachments DROP CONSTRAINT IF EXISTS attachments_duration_ms_check;
            ALTER TABLE __SCHEMA__.attachments ADD CONSTRAINT attachments_duration_ms_check CHECK (duration_ms IS NULL OR duration_ms BETWEEN 1 AND 180000);
            DO $social$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint c
                    JOIN pg_class t ON t.oid = c.conrelid
                    JOIN pg_namespace n ON n.oid = t.relnamespace
                    WHERE c.conname = 'messages_reply_fk' AND n.nspname = '__NAME__'
                ) THEN
                    ALTER TABLE __SCHEMA__.messages
                        ADD CONSTRAINT messages_reply_fk FOREIGN KEY (reply_to)
                        REFERENCES __SCHEMA__.messages(message_id) ON DELETE SET NULL;
                END IF;
            END
            $social$;
            CREATE TABLE IF NOT EXISTS __SCHEMA__.reactions (
                message_id uuid NOT NULL REFERENCES __SCHEMA__.messages(message_id) ON DELETE CASCADE,
                user_id uuid NOT NULL REFERENCES __ACCOUNTS__.users(user_id) ON DELETE CASCADE,
                emoji text NOT NULL CHECK (emoji IN ('like','heart','laugh','wow','sad')),
                created_at timestamptz NOT NULL,
                PRIMARY KEY (message_id, user_id)
            );
            """.Replace("__SCHEMA__", "\"" + name + "\"", StringComparison.Ordinal)
            .Replace("__ACCOUNTS__", accounts.QuotedSchema, StringComparison.Ordinal)
            .Replace("__NAME__", name, StringComparison.Ordinal);
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(ct);
    }
}

internal sealed class SocialSchemaService(AccountsDataSource data, AccountsConfiguration accounts) : Microsoft.Extensions.Hosting.IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken) => SocialSchema.EnsureAsync(data, accounts, cancellationToken);
    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
